#theme: jekyll-theme-cayman
title: 'Azure Machine Learning Workshop'
description: 'This series of workshops will give you hands-on experience on Azure Machine Learning service with Python and dedicated GUI '
remote_theme: azure-immersion/cosmos-jekyll-theme
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
