#theme: jekyll-theme-cayman
title: 'Azure Machine Learning Workshop'
description: 'This series of workshops will give you hands-on experience on Azure Machine Learning service with Python and dedicated GUI '
kramdown:
   syntax_highlighter_opts:
      disable : true
